name: 'Indent PR Review'
description: 'Run Indent AI code reviews on pull requests'
author: 'Indent'

inputs:
  indent-api-key:
    description: 'Indent API key for authentication'
    required: true
  chat-id:
    description: 'Indent chat ID to run'
    required: true
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.12.2'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref || github.head_ref }}

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: |
          **/uv.lock
          **/pyproject.toml

    - name: Login to Indent
      shell: bash
      run: uvx indent login --key ${{ inputs.indent-api-key }}

    - name: Run Indent PR Review
      shell: bash
      env:
        EXPONENT_API_KEY: ${{ inputs.indent-api-key }}
      run: |
        uvx indent run ${{ inputs.chat-id }}

branding:
  icon: 'code-review'
  color: 'blue'
