name: Release

on:
  push:
    branches: [main, pre]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to publish (alpha, pre, etc.)'
        required: false
        default: 'alpha'
        type: string

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Determine which tag to update
          if [[ "${{ github.event_name }}" == "push" ]]; then
            if [[ "${{ github.ref }}" == "refs/heads/pre" ]]; then
              TAG="prerelease"
            else
              TAG="alpha"
            fi
          else
            TAG="${{ github.event.inputs.tag }}"
          fi
          
          # Delete and recreate the tag to point to latest commit
          git tag -d "$TAG" || true
          git push origin ":refs/tags/$TAG" || true
          git tag "$TAG"
          git push origin "$TAG"
          
          echo "✅ Successfully published to @$TAG"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
