name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update beta tag
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Delete and recreate the beta tag to point to latest commit
          git tag -d beta || true
          git push origin :refs/tags/beta || true
          git tag beta
          git push origin beta
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
